name: Build
on:
  push:
    paths-ignore:
      - example/**
      - README.md
    branches:
      - "macos10"
  pull_request:
    paths-ignore:
      - example/**
      - README.md
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for Objective-C files.
      uses: jidicula/clang-format-action@v4.8.0
      with:
        clang-format-version: '13'
  build:
    needs: formatting-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macOS-12
        go:
        - 1.18
        - 1.19
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: cd example/linux && make
      - name: Test
        run: make test
      - name: Test macOS 11 API
        run: make test-macos11
      - name: Test macOS 10 API
        run: make test-macos10
      - name: vet
        run: go vet ./...
  test:
    runs-on: macOS-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: make test
      - name: Test (address sanitizer enabled)
        run: make test-asan
  test-macos11:
    runs-on: macOS-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: make test-macos11
  test-macos10:
    runs-on: macOS-10.15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: make test-macos10
